//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script
ced z:\TestData\configs\rconnectioncmm.xml
run_script z:\TestData\scripts\te_esock_test_loadesock.script

load_suite TE_RConnectionSuite
run_utils DeleteFile c:\rconnectiontest.ini
run_utils CopyFile z:\TestData\configs\rconnectiontest_vlan7.ini c:\rconnectiontest.ini
RUN_UTILS MakeReadWrite c:\rconnectiontest.ini

START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0601
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0601

heap_mark
run_test_step 100, TE_RConnectionSuite Test400 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0601


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0602
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0602

heap_mark
run_test_step 100, TE_RConnectionSuite Test401 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0602


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0603
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0603

heap_mark
run_test_step 100, TE_RConnectionSuite Test402 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0603


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0604
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0604

heap_mark
run_test_step 100, TE_RConnectionSuite Test403 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0604


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0605
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0605

heap_mark
run_test_step 100, TE_RConnectionSuite Test404 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0605


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0606
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0606

heap_mark
run_test_step 100, TE_RConnectionSuite Test405 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0606


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0607
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0607

heap_mark
run_test_step 100, TE_RConnectionSuite Test406 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0607


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0608
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0608

heap_mark
run_test_step 100, TE_RConnectionSuite Test407 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0608


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0609
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0609

heap_mark
run_test_step 100, TE_RConnectionSuite Test408 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0609


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0610
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0610

heap_mark
run_test_step 100, TE_RConnectionSuite Test409 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0610


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0611
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0611

heap_mark
run_test_step 100, TE_RConnectionSuite Test410 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0611


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0612
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0612

heap_mark
run_test_step 100, TE_RConnectionSuite Test411 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0612


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0613
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0613

heap_mark
run_test_step 100, TE_RConnectionSuite Test412 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0613


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0614
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0614

heap_mark
run_test_step 100, TE_RConnectionSuite Test413 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0614


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0615
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0615

heap_mark
run_test_step 100, TE_RConnectionSuite Test414 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0615


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0616
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0616

heap_mark
run_test_step 100, TE_RConnectionSuite Test415 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0616


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0617
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0617

heap_mark
run_test_step 100, TE_RConnectionSuite Test416 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0617


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0618
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0618

heap_mark
run_test_step 100, TE_RConnectionSuite Test417 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0618


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0619
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0619

heap_mark
run_test_step 100, TE_RConnectionSuite Test418 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0619


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0620
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0620

heap_mark
run_test_step 100, TE_RConnectionSuite Test419 c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0620


START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0620b
//! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0620b

heap_mark
run_test_step 100, TE_RConnectionSuite Test419b c:\rconnectiontest.ini
heap_markend
test_complete
END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0620b


//START_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0621
///! @SYMTestCaseID		COMINF-ESOCK-RConnectionSuite-CMM-0621
#heap_mark
#run_test_step 100, TE_RConnectionSuite Test477 c:\rconnectiontest.ini
#heap_markend
#test_complete
//END_TESTCASE			COMINF-ESOCK-RConnectionSuite-CMM-0621


run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script

run_utils MakeReadWrite c:\rconnectiontest.ini
run_utils DeleteFile c:\rconnectiontest.ini


