//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesockForced.script

PRINT TE_ESock_Componentsr: Component Tests
PRINT ------------------------------
PRINT

RUN_UTILS delete c:\system\data\cdbv3.dat
RUN_SCRIPT z:\testdata\scripts\te_dummyprovider_incomingSCPR.script

CED -i z:\testdata\configs\te_dummyproviders.cfg ced.log

RUN_SCRIPT z:\testdata\scripts\te_dummyprovider_001.script
RUN_SCRIPT z:\testdata\scripts\te_dummyprovider_002.script
RUN_SCRIPT z:\testdata\scripts\te_dummyprovider_003.script

RUN_SCRIPT z:\testdata\scripts\te_esock_test_unloadesockForced.script
RUN_SCRIPT z:\testdata\scripts\te_esock_test_remove_config_files.script
